---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by stevenr.
--- DateTime: 2/7/2023 12:04 PM
---

Actor = {
    Gear = {
        head = 0,
        body = 0,
        arms = 0,
        legs = 0,
        feet = 0
    },
    Stats = {
        health = 0,
        attack = 0,
        defend = 0,
        defendBuff = 0,
        attackBuff = 0
    }
};

function Actor:GetStats()
    return Actor.Stats
end

function Actor:SetStats(Actor actor)
    Act
end

print(Actor:GetStats().attack)